Attribute VB_Name = "Form_Formulario1"
Option Compare Database
Option Explicit
Private BotonVerde As CommandButton

Private Sub Form_Load()
    Dim Propiedades As Property
    Dim i As Long
    
'    Debug.Print "CuadroDetalleMaster.BackColor=" & Me.CuadroDetalleMaster.BackColor
'    Debug.Print "CuadroEtiquetaCampoMaster.BackColor=" & Me.CuadroEtiquetaCampoMaster.BackColor
'    Debug.Print "CuadroCampoMaster.BackColor=" & Me.CuadroCampoMaster.BackColor
'    Debug.Print "CuadroListaMaster.BackColor=" & Me.CuadroListaMaster.BackColor
'    Debug.Print "bordercolor=" & Me.CuadroListaMaster.BorderColor
'    Debug.Print "EtiquetaLinkMaster.ForeColor=" & Me.EtiquetaLinkMaster.ForeColor
'    Debug.Print "EtiquetaCampoMaster.ForeColor=" & Me.EtiquetaCampoMaster.ForeColor
    
'    Debug.Print "CuadroDetalleSlave.BackColor=" & Me.CuadroDetalleSlave.BackColor
'    Debug.Print "CuadroEtiquetaCampoSlave.BackColor=" & Me.CuadroEtiquetaCampoSlave.BackColor
'    Debug.Print "CuadroCampoSlave.BackColor=" & Me.CuadroCampoSlave.BackColor
'    Debug.Print "CuadroListaSlave.BackColor=" & Me.CuadroListaSlave.BackColor
'    Debug.Print "bordercolor=" & Me.CuadroListaSlave.BorderColor
'    Debug.Print "EtiquetaLinkSlave.ForeColor=" & Me.EtiquetaLinkSlave.ForeColor
'    Debug.Print "EtiquetaCampoSlave.ForeColor=" & Me.EtiquetaCampoSlave.ForeColor
'    Debug.Print "lblTitulo.ForeColor=" & Me.lblTitulo.ForeColor
    
    
End Sub