VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "CalidadPublicacionResultado"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Public TareasAntes As Long
Public TareasDespues As Long
Public RiesgoInvalidado As EnumSiNo
Public EdicionRehidratada As EnumSiNo
