# HARNESS-PROVENANCE: deterministic quality-harness v1.4 + lanzadera-mvp #621
"""Integration tests for Alembic migrations 0002-0006 (seed data).

TDD contract (gentle-ai RDD):
  RED — tests written before migrations; fail until seed files land.
  GREEN — migrations make the tests pass.
  REFACTOR — seed data is read-only; no refactor expected.

Migration chain: 0001_core_schema → 0002_expedientes_schema →
0003_seed_apps → 0004_seed_profiles → 0005_seed_users →
0006_seed_assignments → 0007_seed_audit.
  REFACTOR — seed data is read-only; no refactor expected.

Each test creates its own fresh database via ``CREATE DATABASE``, runs
``alembic upgrade head`` against it (migrations 0001-0006), verifies the
seeded row counts and representative field values, and drops the database
on teardown. Tests are gated on ``APAP_INTEGRATION_ENABLED=1`` so CI
defaults to skipping them; the local runtime contract runs them with the
flag set.

Fixtures (0002-0006) were generated by
``scripts/generate_lanzadera_fixtures.py`` (seed=42)."""

from __future__ import annotations

import asyncio
import base64
import os
import secrets
import subprocess
import sys
from pathlib import Path

import asyncpg
import pytest

SCHEMA = "lanzadera"

# ---------------------------------------------------------------------------
# Row-count expectations derived from the fixture files (deterministic seed=42).
# ---------------------------------------------------------------------------
EXPECTED_APPS = 20
EXPECTED_PROFILES = 160  # 1 DEFAULT × 20 apps + 7 legacy × 20 apps
EXPECTED_USERS = 156
EXPECTED_ASSIGNMENTS = 622  # active (revoked_at IS NULL)
EXPECTED_AUDIT = 200


PG_HOST = "127.0.0.1"
PG_PORT = 5432
PG_USER = "lanzadera"
PG_PASSWORD = "lanzadera-dev-only"


def _worktree_root() -> Path:
    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / ".git").is_dir() or (parent / ".git").is_file():
            return parent
    raise AssertionError("worktree root not found")


def _alembic_ini_candidates(root: Path) -> list[Path]:
    return [
        root / "app" / "migrations" / "alembic.ini",
        root / "alembic.ini",
    ]


@pytest.fixture(scope="module")
def integration_enabled() -> bool:
    return os.environ.get("APAP_INTEGRATION_ENABLED") == "1"


@pytest.fixture(scope="module")
def worktree_root() -> Path:
    return _worktree_root()


@pytest.fixture(scope="module")
def alembic_ini(worktree_root: Path) -> Path:
    for candidate in _alembic_ini_candidates(worktree_root):
        if candidate.is_file():
            return candidate
    pytest.skip("alembic.ini not found — expected after PR #87")


@pytest.fixture(scope="module")
def test_db_name() -> str:
    return f"lanzadera_seed_test_{secrets.token_hex(4)}"


# Minimal Fernet key (32 bytes, base64url) used in the test environment.
# Same key is set by docker-compose.yml for local dev; tests mirror that contract.
_FIXTURE_KEY = base64.urlsafe_b64encode(b"0" * 32).decode()


@pytest.fixture(scope="module")
def migrated_db(
    integration_enabled: bool,
    worktree_root: Path,
    alembic_ini: Path,
    test_db_name: str,
) -> str:
    if not integration_enabled:
        pytest.skip("APAP_INTEGRATION_ENABLED=1 required for migration tests")
    asyncio.run(_create_test_database(test_db_name))
    try:
        _run_alembic(worktree_root, alembic_ini, test_db_name, "upgrade", "head")
        yield test_db_name
    finally:
        asyncio.run(_drop_test_database(test_db_name))


async def _admin_conn() -> asyncpg.Connection:
    return await asyncpg.connect(
        host=PG_HOST,
        port=PG_PORT,
        user=PG_USER,
        password=PG_PASSWORD,
        database="lanzadera",
    )


async def _create_test_database(name: str) -> None:
    conn = await _admin_conn()
    try:
        await conn.execute(f'DROP DATABASE IF EXISTS "{name}"')
        await conn.execute(f'CREATE DATABASE "{name}"')
    finally:
        await conn.close()


async def _drop_test_database(name: str) -> None:
    conn = await _admin_conn()
    try:
        await conn.execute(
            "SELECT pg_terminate_backend(pid) FROM pg_stat_activity"
            " WHERE datname = $1 AND pid <> pg_backend_pid()",
            name,
        )
        await conn.execute(f'DROP DATABASE IF EXISTS "{name}"')
    finally:
        await conn.close()


def _run_alembic(
    worktree_root: Path,
    alembic_ini: Path,
    db_name: str,
    *args: str,
) -> None:
    database_url = f"postgresql+asyncpg://{PG_USER}:{PG_PASSWORD}@{PG_HOST}:{PG_PORT}/{db_name}"
    env = os.environ.copy()
    env["DATABASE_URL"] = database_url
    env["PLATFORM_SECRET_KEY"] = _FIXTURE_KEY
    env["PYTHONPATH"] = str(worktree_root) + os.pathsep + env.get("PYTHONPATH", "")
    cmd = [sys.executable, "-m", "alembic", "-c", str(alembic_ini), *args]
    result = subprocess.run(
        cmd,
        cwd=worktree_root,
        env=env,
        capture_output=True,
        text=True,
        check=False,
        encoding="utf-8",
    )
    if result.returncode != 0:
        pytest.fail(
            f"alembic {' '.join(args)} failed ({result.returncode}):\n"
            f"STDOUT:\n{result.stdout}\nSTDERR:\n{result.stderr}"
        )


# ---------------------------------------------------------------------------
# RED tests — assert seeded data BEFORE the migration files are written.
# These fail now; they pass once 0002-0006 are in place.
# ---------------------------------------------------------------------------


class TestSeedApps:
    """0002_seed_apps: exactly 20 rows in apps, all active."""

    async def test_row_count(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            count = await conn.fetchval(f"SELECT COUNT(*) FROM {SCHEMA}.apps")
            assert count == EXPECTED_APPS, f"apps: expected {EXPECTED_APPS}, got {count}"
        finally:
            await conn.close()

    async def test_all_active(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            inactive = await conn.fetchval(
                f"SELECT COUNT(*) FROM {SCHEMA}.apps WHERE registration_status != 'active'"
            )
            assert inactive == 0, f"inactive apps: {inactive}"
        finally:
            await conn.close()

    async def test_sample_app(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            row = await conn.fetchrow(
                f"SELECT name, short_code, deployment_topology FROM {SCHEMA}.apps LIMIT 1"
            )
            assert row is not None
            assert row["short_code"] is not None
        finally:
            await conn.close()


class TestSeedProfiles:
    """0003_seed_profiles: exactly 160 rows, capabilities={} provisional."""

    async def test_row_count(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            count = await conn.fetchval(f"SELECT COUNT(*) FROM {SCHEMA}.profiles")
            assert count == EXPECTED_PROFILES, (
                f"profiles: expected {EXPECTED_PROFILES}, got {count}"
            )
        finally:
            await conn.close()

    async def test_capabilities_provisional(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            # G-2: all seeded profiles carry {} until ABIERTO is resolved.
            non_empty = await conn.fetchval(
                f"SELECT COUNT(*) FROM {SCHEMA}.profiles WHERE capabilities != '{{}}'"
            )
            assert non_empty == 0, f"profiles with non-empty capabilities: {non_empty}"
        finally:
            await conn.close()


class TestSeedUsers:
    """0004_seed_users: exactly 156 rows, password_hash=NULL."""

    async def test_row_count(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            count = await conn.fetchval(f"SELECT COUNT(*) FROM {SCHEMA}.users")
            assert count == EXPECTED_USERS, f"users: expected {EXPECTED_USERS}, got {count}"
        finally:
            await conn.close()

    async def test_password_hash_null(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            with_hash = await conn.fetchval(
                f"SELECT COUNT(*) FROM {SCHEMA}.users WHERE password_hash IS NOT NULL"
            )
            assert with_hash == 0, f"users with password_hash: {with_hash}"
        finally:
            await conn.close()

    async def test_status_password_reset_required(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            wrong_status = await conn.fetchval(
                f"SELECT COUNT(*) FROM {SCHEMA}.users WHERE status != 'password_reset_required'"
            )
            assert wrong_status == 0, f"users not in password_reset_required: {wrong_status}"
        finally:
            await conn.close()

    async def test_dni_encrypted_not_null(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            null_dni = await conn.fetchval(
                f"SELECT COUNT(*) FROM {SCHEMA}.users WHERE dni_encrypted IS NULL"
            )
            assert null_dni == 0, f"users with NULL dni_encrypted: {null_dni}"
        finally:
            await conn.close()


class TestSeedAssignments:
    """0005_seed_assignments: exactly 622 active rows."""

    async def test_row_count(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            count = await conn.fetchval(
                f"SELECT COUNT(*) FROM {SCHEMA}.user_app_assignments WHERE revoked_at IS NULL"
            )
            assert count == EXPECTED_ASSIGNMENTS, (
                f"active assignments: expected {EXPECTED_ASSIGNMENTS}, got {count}"
            )
        finally:
            await conn.close()

    async def test_granted_by_null(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            non_null = await conn.fetchval(
                f"SELECT COUNT(*) FROM {SCHEMA}.user_app_assignments"
                " WHERE revoked_at IS NULL AND granted_by IS NOT NULL"
            )
            assert non_null == 0, f"seeded rows with granted_by set: {non_null}"
        finally:
            await conn.close()


class TestSeedAudit:
    """0006_seed_audit: exactly 200 audit events, all module=lanzadera."""

    async def test_row_count(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            count = await conn.fetchval(f"SELECT COUNT(*) FROM {SCHEMA}.audit")
            assert count == EXPECTED_AUDIT, f"audit rows: expected {EXPECTED_AUDIT}, got {count}"
        finally:
            await conn.close()

    async def test_event_types(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            rows = await conn.fetch(
                f"SELECT DISTINCT event_type FROM {SCHEMA}.audit ORDER BY event_type"
            )
            types = [r["event_type"] for r in rows]
            assert set(types).issubset({"auth.login.success", "auth.login.failure", "app.open"}), (
                f"unexpected event types: {types}"
            )
        finally:
            await conn.close()

    async def test_module_lanzadera(self, migrated_db: str) -> None:
        conn = await asyncpg.connect(
            host=PG_HOST, port=PG_PORT, user=PG_USER, password=PG_PASSWORD, database=migrated_db
        )
        try:
            non_lanzadera = await conn.fetchval(
                f"SELECT COUNT(*) FROM {SCHEMA}.audit WHERE module != 'lanzadera'"
            )
            assert non_lanzadera == 0, f"non-lanzadera audit rows: {non_lanzadera}"
        finally:
            await conn.close()
