# HARNESS-PROVENANCE: deterministic-quality-harness v1.4 + lanzadera-mvp PR 3a
# Alembic 1.13 standard Mako template. Modifying this template changes the
# shape of every future migration file generated by `alembic revision`; do
# not edit without coordinating with PR 3b and Phase 4.
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
${imports if imports else ""}

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    """Apply the migration's forward DDL.

    Each step is small enough to read in isolation: extension creation,
    schema creation, ENUM creation, table creation, index creation. The
    order matters — ENUMs must exist before tables reference them; tables
    must exist before indexes reference them. Downgrade reverses every
    step in the opposite order.
    """
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Reverse the migration exactly.

    D82 forbids half-reversible migrations: every DROP must mirror the
    upgrade's CREATE, in reverse order. The convention is to drop indexes
    first, then tables, then ENUMs, then the schema last. `IF EXISTS`
    guards make the downgrade idempotent on partial replays.
    """
    ${downgrades if downgrades else "pass"}