"""AppRepositoryPort.

D7, D52, D85, DA-7. The single source of truth for the platform's
app catalog: identity, deployment topology (central vs office-nas),
office-presence requirement, and registration status. The
``list_active`` read path is the hot path for the delivery layer
(``GET /admin/apps`` and the ``list_visible_to`` permission check);
DA-8 caches it with a 5-minute TTL.

W61 (#524) extended the surface with the admin CRUD operations
(``create`` / ``update`` / ``disable``) so the W61 JSON routes can
mutate the catalog. ``create`` returns the freshly-minted ``App``
(id + server-defaulted timestamps), ``update`` applies the partial
patch and returns the new row, ``disable`` flips
``registration_status`` to ``retired`` and is the only terminal
transition in the lifecycle (DA-7).
"""

from __future__ import annotations

from app.src.modules.lanzadera.domain.app import App, AppTopology
from app.src.modules.lanzadera.domain.ports._imports import (
    UUID,
    Protocol,
    Sequence,
)


class AppRepositoryPort(Protocol):
    """Persistence boundary for the app catalog."""

    async def get_by_id(self, app_id: int) -> App | None:
        """Return the app with ``app_id`` or ``None`` if it does not exist."""
        ...

    async def list_active(self) -> Sequence[App]:
        """Return every app with ``registration_status='active'``.

        Cached with TTL 5 min (DA-8); the cache is invalidated
        when an app's status changes (the ``list_visible_to`` call
        does not use the cache because the visibility check is
        per-user).
        """
        ...

    async def list_visible_to(self, user_id: UUID) -> Sequence[App]:
        """Return every app that ``user_id`` is allowed to see.

        Includes both active and pending apps the user has been
        explicitly granted access to via the assignment table.
        """
        ...

    async def create(
        self,
        name: str,
        short_code: str,
        deployment_topology: AppTopology,
        requires_office_presence: bool,
    ) -> App:
        """Insert a new catalog row and return it with the DB-authoritative id and timestamps.

        W61 (#524): the admin ``POST /admin/apps`` JSON route is the
        first caller. ``id`` is auto-generated by the SERIAL column;
        ``created_at`` / ``updated_at`` are server-defaulted to
        ``now()``. The repo stamps ``registration_status='pending'``
        on insert — the catalog row must be activated by a separate
        flow before non-admin users can see it.
        """
        ...

    async def update(
        self,
        app_id: int,
        *,
        name: str | None = None,
        deployment_topology: AppTopology | None = None,
        requires_office_presence: bool | None = None,
    ) -> App:
        """Apply the partial patch to ``app_id`` and return the new row.

        W61 (#524): the admin ``PATCH /admin/apps/{id}`` route is the
        first caller. ``None`` fields are skipped (the column keeps
        its current value); the touched columns are returned via
        ``RETURNING`` so the caller never sees a stale read.
        """
        ...

    async def disable(self, app_id: int) -> App:
        """Flip ``app_id`` to ``registration_status='retired'`` and return the row.

        W61 (#524): the admin ``DELETE /admin/apps/{id}`` route is the
        first caller. ``disable`` is the terminal transition (DA-7):
        ``retired`` rows are filtered out by ``list_active`` and never
        re-surfaced through the user-facing visibility check.
        """
        ...
