VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "EventoBusqueda"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Public IDEVENTO As String
Public BUI As String
Public SubSistema As String
Public Equipo As String
Public TipoEvento As String
Public FechaInicial As String
Public FechaFinal As String
Public Franqueado As String

